Housing Prices Models

Team Members:
Christopher Ortega
Christian Esqueda
Kayleen Ponce
Horacio Mondragon

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn import preprocessing
from sklearn import metrics
from sklearn.preprocessing import scale
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn import metrics
import matplotlib.pyplot as plt

Here, below, we import the data and place it in a DataFrame

In [3]:
df = pd.DataFrame()
df = pd.read_csv("https://raw.githubusercontent.com/Chris323/FileDump/main/train.csv")
#df.shape

In [4]:
df[0::100]

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
100,101,20,RL,NaN,10603,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2010,WD,Normal,205000
200,201,20,RM,80.0,8546,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,3,2010,WD,Normal,140000
300,301,190,RL,90.0,15750,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2006,WD,Normal,157000
400,401,120,RL,38.0,14963,Pave,NaN,IR2,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,245500
500,501,160,RM,21.0,1890,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,113000
600,601,60,RL,74.0,10927,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2006,WD,Normal,275000
700,701,20,RL,85.0,14331,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2006,WD,Normal,312500
800,801,60,RL,79.0,12798,Pave,NaN,IR1,HLS,AllPub,...,0,NaN,NaN,Shed,400,5,2008,WD,Normal,200000
900,901,20,RL,NaN,7340,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2007,WD,Normal,110000
1000,1001,20,RL,74.0,10206,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2009,WD,Normal,82000
1100,1101,30,RL,60.0,8400,Pave,NaN,Reg,Bnk,AllPub,...,0,NaN,NaN,NaN,0,1,2009,WD,Normal,60000
1200,1201,20,RL,71.0,9353,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,Shed,0,7,2006,Oth,Abnorml,116050
1300,1301,60,RL,NaN,10762,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2009,WD,Normal,225000
1400,1401,50,RM,50.0,6000,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2008,WD,Normal,120000

In [5]:
df.columns.values

array(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
       'BldgType', 'HouseStyle', 'OverallQual', 'OverallCond',
       'YearBuilt', 'YearRemodAdd', 'RoofStyle', 'RoofMatl',
       'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu',
       'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageCars',
       'GarageArea', 'GarageQual', 'GarageCond', 'PavedDrive',
       'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch',
       'ScreenPorch', 'PoolArea', 'PoolQC', 'Fence', 'MiscFeature',
       'MiscVal', 'MoSold', 'YrSold', 'SaleType', 'SaleCondition',
       'SalePrice'], dtype=object)

We make sure to note the shape of the original dataframe.

In [6]:
df.shape

(1460, 81)

Next we create a new DataFrame with only the numerical columns present

In [7]:
numCol = df.select_dtypes(include=['number'])
numCol[0::100]

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,0,61,0,0,0,0,0,2,2008,208500
100,101,20,NaN,10603,6,7,1977,2001,28.0,1200,...,168,68,0,0,0,0,0,2,2010,205000
200,201,20,80.0,8546,4,5,2003,2004,0.0,0,...,132,64,0,0,0,0,0,3,2010,140000
300,301,190,90.0,15750,5,5,1953,1953,56.0,841,...,0,0,0,0,0,0,0,6,2006,157000
400,401,120,38.0,14963,8,5,1996,1996,0.0,786,...,120,30,0,0,224,0,0,12,2008,245500
500,501,160,21.0,1890,6,5,1973,1973,285.0,356,...,144,28,0,0,0,0,0,5,2007,113000
600,601,60,74.0,10927,8,5,2005,2005,280.0,546,...,179,60,0,0,0,0,0,6,2006,275000
700,701,20,85.0,14331,8,5,2002,2002,630.0,1274,...,270,78,0,0,0,0,0,5,2006,312500
800,801,60,79.0,12798,6,5,1997,1997,0.0,462,...,403,114,185,0,0,0,400,5,2008,200000
900,901,20,NaN,7340,4,6,1971,1971,0.0,322,...,0,0,0,0,0,0,0,6,2007,110000
1000,1001,20,74.0,10206,3,3,1952,1952,0.0,0,...,0,0,0,0,0,0,0,7,2009,82000
1100,1101,30,60.0,8400,2,5,1920,1950,0.0,290,...,0,0,0,0,0,0,0,1,2009,60000
1200,1201,20,71.0,9353,4,5,1970,1970,0.0,0,...,0,0,0,0,0,0,0,7,2006,116050
1300,1301,60,NaN,10762,7,5,1999,1999,344.0,694,...,0,0,0,0,0,0,0,5,2009,225000
1400,1401,50,50.0,6000,6,7,1929,1950,0.0,0,...,0,0,112,0,0,0,0,7,2008,120000

We make sure to note the shape of this new DataFrame, it will be needed later.

In [8]:
numCol.shape

(1460, 38)

Next, we create an additional DataFrame with only the catagorical data.

In [9]:
catCol = df.select_dtypes(include=[object])
catCol[0::100]

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
0,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
100,RL,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,NWAmes,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
200,RM,Pave,NaN,Reg,Lvl,AllPub,Corner,Gtl,Edwards,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
300,RL,Pave,NaN,Reg,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,...,Attchd,Unf,TA,TA,Y,NaN,NaN,NaN,WD,Normal
400,RL,Pave,NaN,IR2,Lvl,AllPub,Inside,Gtl,Veenker,Norm,...,Attchd,Fin,TA,TA,Y,NaN,NaN,NaN,WD,Normal
500,RM,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,BrDale,Norm,...,Detchd,Unf,TA,TA,Y,NaN,NaN,NaN,WD,Normal
600,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NridgHt,Norm,...,BuiltIn,Fin,TA,TA,Y,NaN,NaN,NaN,WD,Normal
700,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Timber,Norm,...,Attchd,Fin,TA,TA,Y,NaN,NaN,NaN,WD,Normal
800,RL,Pave,NaN,IR1,HLS,AllPub,Inside,Mod,ClearCr,Feedr,...,Attchd,RFn,TA,TA,Y,NaN,NaN,Shed,WD,Normal
900,RL,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,NAmes,Norm,...,Detchd,Unf,TA,TA,Y,NaN,NaN,NaN,WD,Normal
1000,RL,Pave,NaN,Reg,Lvl,AllPub,Corner,Gtl,Edwards,Norm,...,Detchd,Unf,TA,Fa,Y,NaN,NaN,NaN,WD,Normal
1100,RL,Pave,NaN,Reg,Bnk,AllPub,Inside,Gtl,SWISU,Norm,...,Detchd,Unf,TA,TA,N,NaN,NaN,NaN,WD,Normal
1200,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,...,Attchd,Unf,TA,TA,Y,NaN,NaN,Shed,Oth,Abnorml
1300,RL,Pave,NaN,IR1,Lvl,AllPub,CulDSac,Gtl,Gilbert,Norm,...,Attchd,Fin,TA,TA,Y,NaN,NaN,NaN,WD,Normal
1400,RM,Pave,NaN,Reg,Lvl,AllPub,Corner,Gtl,BrkSide,Norm,...,BuiltIn,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal

We also make note of this shape as well.

In [10]:
catCol.shape

(1460, 43)

We made sure all the catagorical data were set as strings with the command below

In [11]:
catCol = catCol.applymap(str)

We then use LabelEncoder to convert all our catagorical data into numerical values, and we place it in a new DF

In [12]:
le = preprocessing.LabelEncoder()
df2 = catCol.apply(le.fit_transform)

In [13]:
df2[0::100]

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
0,3,1,2,3,3,0,4,0,5,2,...,1,1,4,4,2,3,4,4,8,4
100,3,1,2,0,3,0,4,0,14,2,...,1,1,4,4,2,3,4,4,8,4
200,4,1,2,3,3,0,0,0,7,2,...,1,1,4,4,2,3,4,4,8,4
300,3,1,2,3,3,0,0,0,6,2,...,1,2,4,4,2,3,4,4,8,4
400,3,1,2,1,3,0,4,0,24,2,...,1,0,4,4,2,3,4,4,8,4
500,4,1,2,3,3,0,4,0,2,2,...,5,2,4,4,2,3,4,4,8,4
600,3,1,2,3,3,0,4,0,16,2,...,3,0,4,4,2,3,4,4,8,4
700,3,1,2,3,3,0,4,0,23,2,...,1,0,4,4,2,3,4,4,8,4
800,3,1,2,0,1,0,4,1,4,1,...,1,1,4,4,2,3,4,2,8,4
900,3,1,2,0,3,0,4,0,12,2,...,5,2,4,4,2,3,4,4,8,4
1000,3,1,2,3,3,0,0,0,7,2,...,5,2,4,1,2,3,4,4,8,4
1100,3,1,2,3,0,0,4,0,18,2,...,5,2,4,4,0,3,4,4,8,4
1200,3,1,2,3,3,0,4,0,12,2,...,1,2,4,4,2,3,4,2,7,0
1300,3,1,2,0,3,0,1,0,8,2,...,1,0,4,4,2,3,4,4,8,4
1400,4,1,2,3,3,0,0,0,3,2,...,3,1,4,4,2,3,4,4,8,4

We then took our numerical df (numCol) we created, and the new (previously catagorical) df and merge the columns, creating a new df, in order to have all our data back as one.

In [14]:
frames = [df2, numCol]

dfResult = pd.concat(frames, axis=1)

We then make sure our result df's shape matches our original df's shape.

In [15]:
dfResult.shape

(1460, 81)

In [16]:
dfResult[0::100]

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
0,3,1,2,3,3,0,4,0,5,2,...,0,61,0,0,0,0,0,2,2008,208500
100,3,1,2,0,3,0,4,0,14,2,...,168,68,0,0,0,0,0,2,2010,205000
200,4,1,2,3,3,0,0,0,7,2,...,132,64,0,0,0,0,0,3,2010,140000
300,3,1,2,3,3,0,0,0,6,2,...,0,0,0,0,0,0,0,6,2006,157000
400,3,1,2,1,3,0,4,0,24,2,...,120,30,0,0,224,0,0,12,2008,245500
500,4,1,2,3,3,0,4,0,2,2,...,144,28,0,0,0,0,0,5,2007,113000
600,3,1,2,3,3,0,4,0,16,2,...,179,60,0,0,0,0,0,6,2006,275000
700,3,1,2,3,3,0,4,0,23,2,...,270,78,0,0,0,0,0,5,2006,312500
800,3,1,2,0,1,0,4,1,4,1,...,403,114,185,0,0,0,400,5,2008,200000
900,3,1,2,0,3,0,4,0,12,2,...,0,0,0,0,0,0,0,6,2007,110000
1000,3,1,2,3,3,0,0,0,7,2,...,0,0,0,0,0,0,0,7,2009,82000
1100,3,1,2,3,0,0,4,0,18,2,...,0,0,0,0,0,0,0,1,2009,60000
1200,3,1,2,3,3,0,4,0,12,2,...,0,0,0,0,0,0,0,7,2006,116050
1300,3,1,2,0,3,0,1,0,8,2,...,0,0,0,0,0,0,0,5,2009,225000
1400,4,1,2,3,3,0,0,0,3,2,...,0,0,112,0,0,0,0,7,2008,120000

In [17]:
scaled_df = scale(dfResult)

In [19]:
#scaled_df.columns.values

In [149]:
dfFinal = pd.DataFrame(data = scaled_df, columns = dfResult.columns.values)
dfFinal = dfFinal.reset_index()

In [150]:
feature_columns = dfFinal[dfFinal.columns.values]
x = feature_columns.drop(['SalePrice'], axis=1)
y = dfFinal['SalePrice']

In [151]:
#x.shape
#y.shape

In [152]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state = 6)

In [153]:
myADA = AdaBoostRegressor()
myADA.fit(x_train, y_train)
myADA_y_predict = myADA.predict(x_test)
myADA_mse = metrics.mean_squared_error(y_test, myADA_y_predict)
myADA_rmse = np.sqrt(myADA_mse)
final_dataset.append(myADA_y_predict)
#final_dataset
#myADA_y_predict

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').